version: ~> 1.0

env:
  global:
    # doctr generated secure variable for documentation upload
    - secure: "<your secure here>"
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="{{ cookiecutter.import_name }}"

    # The name of the conda package
    - CONDA_PACKAGE="{{ cookiecutter.import_name }}"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

{% if cookiecutter.use_x11_on_travis == "yes" %}
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip pyqt=5"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="PyQt5"
{% endif %}

# Uncomment this block if you would like to make PIP test an allowed failure
#jobs:
#  allow_failures:
#    # This makes the PIP based Python 3.6 optional for passing.
#    # Remove this block if passing tests with PIP is mandatory for your
#    # package
#    - name: "Python 3.6 - PIP"

import:
{% if cookiecutter.use_x11_on_travis == "yes" %}
  # If your project requires X11 leave the following import
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
{% endif %}
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
#language: python
#os: linux
#dist: xenial
#
#stages:
#  - build
#  - test
#  - name: deploy
#    if: (branch = master OR tag IS present) AND type != pull_request
#
#import:
#  # Build Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
#  # Tests Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-pip.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-conda.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-linter.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/docs-build.yml
#  # Deploy Stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
